/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jazz;

import javax.swing.JOptionPane;

/**
 *
 * @author DEll
 */
public class InternetForm extends javax.swing.JFrame {

    int index = -1;
    
    /**
     * Creates new form InternetForm
     */
    public InternetForm() {
        initComponents();
    }
    
    public InternetForm(int index) {
        initComponents();
        this.index=index;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        wtsapp = new javax.swing.JTextField();
        instagram = new javax.swing.JTextField();
        facebook = new javax.swing.JTextField();
        youtube = new javax.swing.JTextField();
        google = new javax.swing.JTextField();
        invalidWtsapp = new javax.swing.JLabel();
        invalidInstagram = new javax.swing.JLabel();
        invalidFacebook = new javax.swing.JLabel();
        invalidYoutube = new javax.swing.JLabel();
        invalidGoogle = new javax.swing.JLabel();
        usebutton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Internet Usage");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jazz/jazzbgd.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 72)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(251, 255, 0));
        jLabel2.setText("Management System");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(248, 1, 1));
        jLabel3.setText("INTERNET USE");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 0));
        jLabel4.setText("WhatsApp :");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(253, 84, 4));
        jLabel5.setText("Instagram :");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("FaceBook :");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("YouTube :");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(251, 255, 0));
        jLabel8.setText("Google :");

        wtsapp.setBackground(new java.awt.Color(0, 0, 0));
        wtsapp.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        wtsapp.setForeground(new java.awt.Color(255, 255, 255));
        wtsapp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        instagram.setBackground(new java.awt.Color(0, 0, 0));
        instagram.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        instagram.setForeground(new java.awt.Color(255, 255, 255));
        instagram.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        facebook.setBackground(new java.awt.Color(0, 0, 0));
        facebook.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        facebook.setForeground(new java.awt.Color(255, 255, 255));
        facebook.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        youtube.setBackground(new java.awt.Color(0, 0, 0));
        youtube.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        youtube.setForeground(new java.awt.Color(255, 255, 255));
        youtube.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        google.setBackground(new java.awt.Color(0, 0, 0));
        google.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        google.setForeground(new java.awt.Color(255, 255, 255));
        google.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        invalidWtsapp.setBackground(new java.awt.Color(0, 0, 0));
        invalidWtsapp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        invalidWtsapp.setForeground(new java.awt.Color(255, 255, 255));

        invalidInstagram.setBackground(new java.awt.Color(0, 0, 0));
        invalidInstagram.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        invalidInstagram.setForeground(new java.awt.Color(255, 255, 255));

        invalidFacebook.setBackground(new java.awt.Color(0, 0, 0));
        invalidFacebook.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        invalidFacebook.setForeground(new java.awt.Color(255, 255, 255));

        invalidYoutube.setBackground(new java.awt.Color(0, 0, 0));
        invalidYoutube.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        invalidYoutube.setForeground(new java.awt.Color(255, 255, 255));

        invalidGoogle.setBackground(new java.awt.Color(0, 0, 0));
        invalidGoogle.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        invalidGoogle.setForeground(new java.awt.Color(255, 255, 255));

        usebutton.setBackground(new java.awt.Color(204, 0, 0));
        usebutton.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        usebutton.setForeground(new java.awt.Color(204, 204, 204));
        usebutton.setText("USE");
        usebutton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 255, 0), 3));
        usebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usebuttonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(0, 0, 204));
        cancelButton.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(204, 204, 204));
        cancelButton.setText("CANCEL");
        cancelButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 255, 0), 3));
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(89, 89, 89))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(invalidInstagram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wtsapp)
                    .addComponent(instagram, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(facebook, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(youtube, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(google, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(invalidWtsapp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(invalidFacebook, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(invalidYoutube, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(invalidGoogle, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(usebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(wtsapp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invalidWtsapp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(instagram, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invalidInstagram, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(facebook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invalidFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(youtube, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invalidYoutube, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(google, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invalidGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        Usage use = new Usage(index);
        use.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void usebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usebuttonActionPerformed
        // TODO add your handling code here:
        String Whatsapp=wtsapp.getText();
        String insta=instagram.getText();
        String fb=facebook.getText();
        String you=youtube.getText();
        String gogle=google.getText();
        String check="";
        if(Whatsapp.equals("") || Whatsapp.equals(null))
        {
            invalidWtsapp.setText("(You Box is Empty)");
            check="a";
        }
        if(insta.equals("") || insta.equals(null))
        {
            invalidInstagram.setText("(You Box is Empty)");
            check="a";
        }
        if(fb.equals("") || fb.equals(null))
        {
            invalidFacebook.setText("(You Box is Empty)");
            check="a";
        }
        if(you.equals("") || you.equals(null))
        {
            invalidYoutube.setText("(You Box is Empty)");
            check="a";
        }
        if(google.equals("") || google.equals(null))
        {
            invalidGoogle.setText("(You Box is Empty)");
            check="a";
        }
   /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
   
        if(check.equals(""))
        {
            boolean flag=false;
            check="";
            for(int i=0;i<Whatsapp.length();i++)
            {
                if(Whatsapp.charAt(i)>='0' && Whatsapp.charAt(i)<='9')
                {
                    flag=true;
                }
                else
                {
                    flag=false;
                    check="a";
                    break;
                }
            }
            if(!flag)
            {
                invalidWtsapp.setText("Count should be in Digits");
            }
            
            flag=false;
            for(int i=0;i<insta.length();i++)
            {
                if(insta.charAt(i)>='0' && insta.charAt(i)<='9')
                {
                    flag=true;
                }
                else
                {
                    flag=false;
                    check="a";
                    break;
                }
            }
            if(!flag)
            {
                invalidInstagram.setText("Count should be in Digits");
            }
            
            flag=false;
            for(int i=0;i<fb.length();i++)
            {
                if(fb.charAt(i)>='0' && fb.charAt(i)<='9')
                {
                    flag=true;
                }
                else
                {
                    flag=false;
                    check="a";
                    break;
                }
            }
            if(!flag)
            {
                invalidFacebook.setText("Count should be in Digits");
            }
            
            flag=false;
            for(int i=0;i<you.length();i++)
            {
                if(you.charAt(i)>='0' && you.charAt(i)<='9')
                {
                    flag=true;
                }
                else
                {
                    flag=false;
                    check="a";
                    break;
                }
            }
            if(!flag)
            {
                invalidYoutube.setText("Count should be in Digits");
            }
            
            flag=false;
            for(int i=0;i<gogle.length();i++)
            {
                if(gogle.charAt(i)>='0' && gogle.charAt(i)<='9')
                {
                    flag=true;
                }
                else
                {
                    flag=false;
                    check="a";
                    break;
                }
            }
            if(!flag)
            {
                invalidGoogle.setText("Count should be in Digits");
            }
            
            if(check.equals(""))
            {
                int wAmount=Integer.parseInt(Whatsapp);
                int iAmount=Integer.parseInt(insta);
                int fAmount=Integer.parseInt(fb);
                int uAmount=Integer.parseInt(you);
                int gAmount=Integer.parseInt(gogle);
                check="";
                if(wAmount>=0 && wAmount<=50)
                {}
                else
                {
                    check="a";
                    invalidWtsapp.setText("It shoud be in from 0 to 50");
                }
                if(iAmount>=0 && iAmount<=50)
                {}
                else
                {
                    check="a";
                    invalidInstagram.setText("It shoud be in from 0 to 50");
                }
                if(fAmount>=0 && fAmount<=50)
                {}
                else
                {
                    check="a";
                    invalidFacebook.setText("It shoud be in from 0 to 50");
                }
                if(uAmount>=0 && uAmount<=50)
                {}
                else
                {
                    check="a";
                    invalidYoutube.setText("It shoud be in from 0 to 50");
                }
                if(gAmount>=0 && gAmount<=50)
                {}
                else
                {
                    check="a";
                    invalidGoogle.setText("It shoud be in from 0 to 50");
                }
                
                if(check.equals(""))
                {
                    wAmount=wAmount*13;
                    iAmount=wAmount*15;
                    fAmount=wAmount*17;
                    uAmount=wAmount*20;
                    gAmount=wAmount*25;
                    int total=wAmount+iAmount+fAmount+uAmount+gAmount;
                    if(JazzWorld.worldInstance().getInternet().get(index).GetNumberOfMBS()>=total)
                    {
                        JazzWorld.worldInstance().getInternet().get(index).SetNumberOfMBS(JazzWorld.worldInstance().getInternet().get(index).GetNumberOfMBS()-total);
                        JOptionPane.showMessageDialog(this,"You used "+total+" MBs of the Data","Timeline",JOptionPane.INFORMATION_MESSAGE);
                        JazzWorld.worldInstance().writeIntData();
                        WorldCustomerMenu menu = new WorldCustomerMenu(index);
                        menu.setVisible(true);
                        this.dispose();
                    }
                    else
                      JOptionPane.showMessageDialog(this,"You Dont have Enough MBs","Timeline",JOptionPane.ERROR_MESSAGE);  
                    
                    
                }
            }
        }
        
    }//GEN-LAST:event_usebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InternetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InternetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InternetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InternetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InternetForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField facebook;
    private javax.swing.JTextField google;
    private javax.swing.JTextField instagram;
    private javax.swing.JLabel invalidFacebook;
    private javax.swing.JLabel invalidGoogle;
    private javax.swing.JLabel invalidInstagram;
    private javax.swing.JLabel invalidWtsapp;
    private javax.swing.JLabel invalidYoutube;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton usebutton;
    private javax.swing.JTextField wtsapp;
    private javax.swing.JTextField youtube;
    // End of variables declaration//GEN-END:variables
}
